# Generated by Django 4.1.7 on 2023-03-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesong', models.TextField(max_length=50)),
                ('singer1', models.TextField(max_length=30)),
                ('singer2', models.TextField(max_length=30)),
                ('singer3', models.TextField(max_length=30)),
                ('typeSong', models.TextField(max_length=30)),
                ('week1', models.DateField(max_length=30)),
                ('week2', models.DateField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='imagebd/')),
            ],
        ),
    ]
